"""empty message

Revision ID: 7bc868202332
Revises: d0cd6e75eea2
Create Date: 2024-01-26 20:18:12.755052

"""


# revision identifiers, used by Alembic.
revision = "7bc868202332"
down_revision = "d0cd6e75eea2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
