"""empty message

Revision ID: 4b359d1a6081
Revises: 
Create Date: 2024-01-26 15:42:30.664551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4b359d1a6081"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "game",
        sa.Column("white_id", sa.Integer(), nullable=True),
        sa.Column("black_id", sa.Integer(), nullable=True),
        sa.Column(
            "stage",
            sa.Enum("waiting", "playing", "ended", name="stage"),
            nullable=False,
        ),
        sa.Column(
            "outcome",
            sa.Enum("checkmate", "draw", "abandoned", name="result"),
            nullable=True,
        ),
        sa.Column("winner", sa.Enum("white", "black", name="color"), nullable=True),
        sa.Column("fen", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["black_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["white_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "move",
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("move", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["game.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("move")
    op.drop_table("game")
    op.drop_table("user")
    # ### end Alembic commands ###
